// <auto-generated />
namespace ITJob.SecurityService.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sp1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sp1));
        
        string IMigrationMetadata.Id
        {
            get { return "201610171154208_sp1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
